name: Release

on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - '*.x' # maintenance releases

jobs:
  release-library:
    runs-on: ubuntu-latest
    if: github.repository == 'yethranayeh/react95-tailwind'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Deploy library
        if: ${{ secrets.NPM_TOKEN != '' }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
